<?php
// database/seeders/ImprimanteSeeder.php

namespace Database\Seeders;

use App\Models\Imprimante;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ImprimanteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $imprimantes = [
            // === INFORMATIQUE (8 imprimantes) ===
            [
                'nom' => 'IMP-IT-001',
                'entite' => 'Informatique',
                'statut' => 'En service',
                'fabricant' => 'HP',
                'reseau_ip' => '192.168.1.50',
                'numero_serie' => 'SNHP123456789',
                'lieu' => 'Salle Serveur Bâtiment A',
                'type' => 'Laser',
                'modele' => 'LaserJet Pro M404dn',
                'created_at' => Carbon::now()->subYears(2),
                'updated_at' => Carbon::now()->subDays(15),
            ],
            [
                'nom' => 'IMP-IT-002',
                'entite' => 'Informatique',
                'statut' => 'En service',
                'fabricant' => 'Canon',
                'reseau_ip' => '192.168.1.51',
                'numero_serie' => 'SNCA987654321',
                'lieu' => 'Bureau Support IT',
                'type' => 'Multifonction',
                'modele' => 'imageRUNNER ADVANCE C3530i',
                'created_at' => Carbon::now()->subYear(),
                'updated_at' => Carbon::now()->subDays(3),
            ],
            [
                'nom' => 'IMP-IT-003',
                'entite' => 'Informatique',
                'statut' => 'En maintenance',
                'fabricant' => 'Brother',
                'reseau_ip' => '192.168.1.52',
                'numero_serie' => 'SNBR111222333',
                'lieu' => 'Labo Développement',
                'type' => 'Laser',
                'modele' => 'HL-L8360CDW',
                'created_at' => Carbon::now()->subMonths(8),
                'updated_at' => Carbon::now()->subDay(),
            ],
            [
                'nom' => 'IMP-IT-004',
                'entite' => 'Informatique',
                'statut' => 'En service',
                'fabricant' => 'Epson',
                'reseau_ip' => '192.168.1.53',
                'numero_serie' => 'SNEP444555666',
                'lieu' => 'Salle Réseau',
                'type' => 'Jet d\'encre',
                'modele' => 'WorkForce Pro WF-4740',
                'created_at' => Carbon::now()->subMonths(6),
                'updated_at' => Carbon::now()->subDays(7),
            ],
            [
                'nom' => 'IMP-IT-005',
                'entite' => 'Informatique',
                'statut' => 'Hors service',
                'fabricant' => 'Lexmark',
                'reseau_ip' => '192.168.1.54',
                'numero_serie' => 'SNLM777888999',
                'lieu' => 'Local Technique',
                'type' => 'Laser',
                'modele' => 'MX421ade',
                'created_at' => Carbon::now()->subYears(3),
                'updated_at' => Carbon::now()->subMonths(2),
            ],
            [
                'nom' => 'IMP-IT-006',
                'entite' => 'Informatique',
                'statut' => 'En service',
                'fabricant' => 'HP',
                'reseau_ip' => '192.168.1.55',
                'numero_serie' => 'SNHP222333444',
                'lieu' => 'Help Desk',
                'type' => 'Laser',
                'modele' => 'LaserJet Pro MFP M428fdw',
                'created_at' => Carbon::now()->subMonths(4),
                'updated_at' => Carbon::now()->subDays(2),
            ],
            [
                'nom' => 'IMP-IT-007',
                'entite' => 'Informatique',
                'statut' => 'En stock',
                'fabricant' => 'Canon',
                'reseau_ip' => null,
                'numero_serie' => 'SNCA555666777',
                'lieu' => 'Réserve IT',
                'type' => 'Multifonction',
                'modele' => 'imageCLASS MF644Cdw',
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subDays(30),
            ],
            [
                'nom' => 'IMP-IT-008',
                'entite' => 'Informatique',
                'statut' => 'En service',
                'fabricant' => 'Brother',
                'reseau_ip' => '192.168.1.56',
                'numero_serie' => 'SNBR888999000',
                'lieu' => 'Bureau Admin Système',
                'type' => 'Laser',
                'modele' => 'HL-L8260CDW',
                'created_at' => Carbon::now()->subMonths(10),
                'updated_at' => Carbon::now()->subDays(5),
            ],

            // === RESSOURCES HUMAINES (6 imprimantes) ===
            [
                'nom' => 'IMP-RH-001',
                'entite' => 'Ressources Humaines',
                'statut' => 'En service',
                'fabricant' => 'HP',
                'reseau_ip' => '192.168.1.60',
                'numero_serie' => 'SNHP666777888',
                'lieu' => 'Bureau RH 201',
                'type' => 'Laser',
                'modele' => 'LaserJet Pro M404n',
                'created_at' => Carbon::now()->subMonths(18),
                'updated_at' => Carbon::now()->subWeek(),
            ],
            [
                'nom' => 'IMP-RH-002',
                'entite' => 'Ressources Humaines',
                'statut' => 'En service',
                'fabricant' => 'Canon',
                'reseau_ip' => '192.168.1.61',
                'numero_serie' => 'SNCA111222333',
                'lieu' => 'Bureau Recrutement',
                'type' => 'Multifonction',
                'modele' => 'PIXMA TR8550',
                'created_at' => Carbon::now()->subMonths(9),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'nom' => 'IMP-RH-003',
                'entite' => 'Ressources Humaines',
                'statut' => 'En maintenance',
                'fabricant' => 'Epson',
                'reseau_ip' => '192.168.1.62',
                'numero_serie' => 'SNEP777888999',
                'lieu' => 'Bureau Formation',
                'type' => 'Jet d\'encre',
                'modele' => 'WorkForce WF-2860',
                'created_at' => Carbon::now()->subMonths(12),
                'updated_at' => Carbon::now()->subDay(),
            ],
            [
                'nom' => 'IMP-RH-004',
                'entite' => 'Ressources Humaines',
                'statut' => 'En service',
                'fabricant' => 'Brother',
                'reseau_ip' => '192.168.1.63',
                'numero_serie' => 'SNBR333444555',
                'lieu' => 'Salle Archives RH',
                'type' => 'Laser',
                'modele' => 'HL-L8350CDW',
                'created_at' => Carbon::now()->subMonths(6),
                'updated_at' => Carbon::now()->subDays(3),
            ],
            [
                'nom' => 'IMP-RH-005',
                'entite' => 'Ressources Humaines',
                'statut' => 'Hors service',
                'fabricant' => 'HP',
                'reseau_ip' => null,
                'numero_serie' => 'SNHP999000111',
                'lieu' => 'Local Stockage',
                'type' => 'Laser',
                'modele' => 'LaserJet P1102',
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subMonths(3),
            ],
            [
                'nom' => 'IMP-RH-006',
                'entite' => 'Ressources Humaines',
                'statut' => 'En stock',
                'fabricant' => 'Canon',
                'reseau_ip' => null,
                'numero_serie' => 'SNCA444555666',
                'lieu' => 'Réserve RH',
                'type' => 'Multifonction',
                'modele' => 'MAXIFY GX4020',
                'created_at' => Carbon::now()->subMonths(1),
                'updated_at' => Carbon::now()->subDays(15),
            ],

            // === COMMERCIAL (8 imprimantes) ===
            [
                'nom' => 'IMP-COM-001',
                'entite' => 'Commercial',
                'statut' => 'En service',
                'fabricant' => 'Epson',
                'reseau_ip' => '192.168.1.70',
                'numero_serie' => 'SNEP555666777',
                'lieu' => 'Espace Commercial Open Space',
                'type' => 'Jet d\'encre',
                'modele' => 'WorkForce WF-7820',
                'created_at' => Carbon::now()->subMonths(9),
                'updated_at' => Carbon::now()->subDays(2),
            ],
            [
                'nom' => 'IMP-COM-002',
                'entite' => 'Commercial',
                'statut' => 'En maintenance',
                'fabricant' => 'HP',
                'reseau_ip' => '192.168.1.71',
                'numero_serie' => 'SNHP444555666',
                'lieu' => 'Bureau Chef des Ventes',
                'type' => 'Laser',
                'modele' => 'LaserJet Pro M203dw',
                'created_at' => Carbon::now()->subMonths(6),
                'updated_at' => Carbon::now()->subDay(),
            ],
            [
                'nom' => 'IMP-COM-003',
                'entite' => 'Commercial',
                'statut' => 'En service',
                'fabricant' => 'Canon',
                'reseau_ip' => '192.168.1.72',
                'numero_serie' => 'SNCA888999000',
                'lieu' => 'Bureau Équipe Ouest',
                'type' => 'Multifonction',
                'modele' => 'PIXMA TS8350',
                'created_at' => Carbon::now()->subMonths(7),
                'updated_at' => Carbon::now()->subDays(4),
            ],
            [
                'nom' => 'IMP-COM-004',
                'entite' => 'Commercial',
                'statut' => 'En service',
                'fabricant' => 'Brother',
                'reseau_ip' => '192.168.1.73',
                'numero_serie' => 'SNBR222333444',
                'lieu' => 'Bureau Équipe Est',
                'type' => 'Laser',
                'modele' => 'HL-L3210CW',
                'created_at' => Carbon::now()->subMonths(5),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'nom' => 'IMP-COM-005',
                'entite' => 'Commercial',
                'statut' => 'En service',
                'fabricant' => 'HP',
                'reseau_ip' => '192.168.1.74',
                'numero_serie' => 'SNHP777888999',
                'lieu' => 'Salle Réunion Commerciale',
                'type' => 'Laser',
                'modele' => 'LaserJet Pro MFP M130fw',
                'created_at' => Carbon::now()->subMonths(3),
                'updated_at' => Carbon::now()->subHours(5),
            ],
            [
                'nom' => 'IMP-COM-006',
                'entite' => 'Commercial',
                'statut' => 'Hors service',
                'fabricant' => 'Epson',
                'reseau_ip' => null,
                'numero_serie' => 'SNEP111222333',
                'lieu' => 'Local Technique',
                'type' => 'Jet d\'encre',
                'modele' => 'Stylus SX235W',
                'created_at' => Carbon::now()->subYears(4),
                'updated_at' => Carbon::now()->subMonths(1),
            ],
            [
                'nom' => 'IMP-COM-007',
                'entite' => 'Commercial',
                'statut' => 'En stock',
                'fabricant' => 'Canon',
                'reseau_ip' => null,
                'numero_serie' => 'SNCA666777888',
                'lieu' => 'Réserve Commercial',
                'type' => 'Multifonction',
                'modele' => 'PIXMA TR150',
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subDays(20),
            ],
            [
                'nom' => 'IMP-COM-008',
                'entite' => 'Commercial',
                'statut' => 'En service',
                'fabricant' => 'HP',
                'reseau_ip' => '192.168.1.75',
                'numero_serie' => 'SNHP000111222',
                'lieu' => 'Bureau Téléprospection',
                'type' => 'Laser',
                'modele' => 'LaserJet Pro M15w',
                'created_at' => Carbon::now()->subMonths(8),
                'updated_at' => Carbon::now()->subDays(6),
            ],

            // === DIRECTION (5 imprimantes) ===
            [
                'nom' => 'IMP-DIR-001',
                'entite' => 'Direction',
                'statut' => 'En service',
                'fabricant' => 'Xerox',
                'reseau_ip' => '192.168.1.80',
                'numero_serie' => 'SNXE777888999',
                'lieu' => 'Bureau du Directeur Général',
                'type' => 'Multifonction',
                'modele' => 'VersaLink C400',
                'created_at' => Carbon::now()->subMonths(3),
                'updated_at' => Carbon::now()->subHours(5),
            ],
            [
                'nom' => 'IMP-DIR-002',
                'entite' => 'Direction',
                'statut' => 'En service',
                'fabricant' => 'HP',
                'reseau_ip' => '192.168.1.81',
                'numero_serie' => 'SNHP333444555',
                'lieu' => 'Bureau DAF',
                'type' => 'Laser',
                'modele' => 'LaserJet Enterprise M506dn',
                'created_at' => Carbon::now()->subMonths(7),
                'updated_at' => Carbon::now()->subHours(12),
            ],
            [
                'nom' => 'IMP-DIR-003',
                'entite' => 'Direction',
                'statut' => 'En service',
                'fabricant' => 'Canon',
                'reseau_ip' => '192.168.1.82',
                'numero_serie' => 'SNCA222333444',
                'lieu' => 'Bureau DRH',
                'type' => 'Multifonction',
                'modele' => 'imageRUNNER 2204N',
                'created_at' => Carbon::now()->subMonths(5),
                'updated_at' => Carbon::now()->subDays(2),
            ],
            [
                'nom' => 'IMP-DIR-004',
                'entite' => 'Direction',
                'statut' => 'En maintenance',
                'fabricant' => 'Epson',
                'reseau_ip' => '192.168.1.83',
                'numero_serie' => 'SNEP888999000',
                'lieu' => 'Bureau DSI',
                'type' => 'Jet d\'encre',
                'modele' => 'WorkForce Pro WF-4830',
                'created_at' => Carbon::now()->subMonths(4),
                'updated_at' => Carbon::now()->subDay(),
            ],
            [
                'nom' => 'IMP-DIR-005',
                'entite' => 'Direction',
                'statut' => 'En stock',
                'fabricant' => 'HP',
                'reseau_ip' => null,
                'numero_serie' => 'SNHP555666777',
                'lieu' => 'Réserve Direction',
                'type' => 'Laser',
                'modele' => 'LaserJet Pro MFP M227fdw',
                'created_at' => Carbon::now()->subMonths(1),
                'updated_at' => Carbon::now()->subDays(10),
            ],

            // === COMPTABILITÉ (6 imprimantes) ===
            [
                'nom' => 'IMP-COMPTA-001',
                'entite' => 'Comptabilité',
                'statut' => 'En service',
                'fabricant' => 'Lexmark',
                'reseau_ip' => '192.168.1.90',
                'numero_serie' => 'SNLM333222111',
                'lieu' => 'Service Comptabilité - Bureau 301',
                'type' => 'Laser',
                'modele' => 'MX421ade',
                'created_at' => Carbon::now()->subYears(3),
                'updated_at' => Carbon::now()->subDays(7),
            ],
            [
                'nom' => 'IMP-COMPTA-002',
                'entite' => 'Comptabilité',
                'statut' => 'En service',
                'fabricant' => 'HP',
                'reseau_ip' => '192.168.1.91',
                'numero_serie' => 'SNHP111222333',
                'lieu' => 'Bureau Comptable 302',
                'type' => 'Laser',
                'modele' => 'LaserJet Pro M404dw',
                'created_at' => Carbon::now()->subMonths(10),
                'updated_at' => Carbon::now()->subDays(3),
            ],
            [
                'nom' => 'IMP-COMPTA-003',
                'entite' => 'Comptabilité',
                'statut' => 'En maintenance',
                'fabricant' => 'Brother',
                'reseau_ip' => '192.168.1.92',
                'numero_serie' => 'SNBR444555666',
                'lieu' => 'Bureau Paie 303',
                'type' => 'Multifonction',
                'modele' => 'MFC-L2710DW',
                'created_at' => Carbon::now()->subMonths(8),
                'updated_at' => Carbon::now()->subDay(),
            ],
            [
                'nom' => 'IMP-COMPTA-004',
                'entite' => 'Comptabilité',
                'statut' => 'En service',
                'fabricant' => 'Canon',
                'reseau_ip' => '192.168.1.93',
                'numero_serie' => 'SNCA777888999',
                'lieu' => 'Salle Archives Compta',
                'type' => 'Laser',
                'modele' => 'i-SENSYS LBP6230dn',
                'created_at' => Carbon::now()->subMonths(12),
                'updated_at' => Carbon::now()->subDays(5),
            ],
            [
                'nom' => 'IMP-COMPTA-005',
                'entite' => 'Comptabilité',
                'statut' => 'Hors service',
                'fabricant' => 'Epson',
                'reseau_ip' => null,
                'numero_serie' => 'SNEP222333444',
                'lieu' => 'Local Stockage',
                'type' => 'Jet d\'encre',
                'modele' => 'WorkForce WF-2750',
                'created_at' => Carbon::now()->subYears(2),
                'updated_at' => Carbon::now()->subMonths(4),
            ],
            [
                'nom' => 'IMP-COMPTA-006',
                'entite' => 'Comptabilité',
                'statut' => 'En stock',
                'fabricant' => 'HP',
                'reseau_ip' => null,
                'numero_serie' => 'SNHP888999000',
                'lieu' => 'Réserve Comptabilité',
                'type' => 'Laser',
                'modele' => 'LaserJet Pro M15a',
                'created_at' => Carbon::now()->subMonths(3),
                'updated_at' => Carbon::now()->subDays(25),
            ],

            // === MARKETING (5 imprimantes) ===
            [
                'nom' => 'IMP-MKT-001',
                'entite' => 'Marketing',
                'statut' => 'En service',
                'fabricant' => 'Epson',
                'reseau_ip' => '192.168.1.100',
                'numero_serie' => 'SNEP888999000',
                'lieu' => 'Service Marketing - Salle Créa',
                'type' => 'Jet d\'encre',
                'modele' => 'SureColor P700',
                'created_at' => Carbon::now()->subMonths(4),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'nom' => 'IMP-MKT-002',
                'entite' => 'Marketing',
                'statut' => 'En service',
                'fabricant' => 'Canon',
                'reseau_ip' => '192.168.1.101',
                'numero_serie' => 'SNCA000111222',
                'lieu' => 'Bureau Chef Marketing',
                'type' => 'Multifonction',
                'modele' => 'PIXMA G6020',
                'created_at' => Carbon::now()->subMonths(6),
                'updated_at' => Carbon::now()->subDays(2),
            ],
            [
                'nom' => 'IMP-MKT-003',
                'entite' => 'Marketing',
                'statut' => 'En maintenance',
                'fabricant' => 'HP',
                'reseau_ip' => '192.168.1.102',
                'numero_serie' => 'SNHP222333444',
                'lieu' => 'Bureau Équipe Digital',
                'type' => 'Laser',
                'modele' => 'LaserJet Pro MFP M227fdn',
                'created_at' => Carbon::now()->subMonths(8),
                'updated_at' => Carbon::now()->subDay(),
            ],
            [
                'nom' => 'IMP-MKT-004',
                'entite' => 'Marketing',
                'statut' => 'En service',
                'fabricant' => 'Brother',
                'reseau_ip' => '192.168.1.103',
                'numero_serie' => 'SNBR555666777',
                'lieu' => 'Salle Événementiel',
                'type' => 'Laser',
                'modele' => 'HL-L8260CDW',
                'created_at' => Carbon::now()->subMonths(3),
                'updated_at' => Carbon::now()->subDays(4),
            ],
            [
                'nom' => 'IMP-MKT-005',
                'entite' => 'Marketing',
                'statut' => 'En stock',
                'fabricant' => 'Epson',
                'reseau_ip' => null,
                'numero_serie' => 'SNEP333444555',
                'lieu' => 'Réserve Marketing',
                'type' => 'Jet d\'encre',
                'modele' => 'WorkForce WF-7210',
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subDays(18),
            ],

            // === PRODUCTION (4 imprimantes) ===
            [
                'nom' => 'IMP-PROD-001',
                'entite' => 'Production',
                'statut' => 'En service',
                'fabricant' => 'Zebra',
                'reseau_ip' => '192.168.2.10',
                'numero_serie' => 'SNZB123456789',
                'lieu' => 'Atelier Production - Ligne A',
                'type' => 'Thermique',
                'modele' => 'ZT410',
                'created_at' => Carbon::now()->subMonths(8),
                'updated_at' => Carbon::now()->subDays(10),
            ],
            [
                'nom' => 'IMP-PROD-002',
                'entite' => 'Production',
                'statut' => 'En service',
                'fabricant' => 'Zebra',
                'reseau_ip' => '192.168.2.11',
                'numero_serie' => 'SNZB987654321',
                'lieu' => 'Atelier Production - Ligne B',
                'type' => 'Thermique',
                'modele' => 'ZT230',
                'created_at' => Carbon::now()->subMonths(7),
                'updated_at' => Carbon::now()->subDays(8),
            ],
            [
                'nom' => 'IMP-PROD-003',
                'entite' => 'Production',
                'statut' => 'En maintenance',
                'fabricant' => 'Brother',
                'reseau_ip' => '192.168.2.12',
                'numero_serie' => 'SNBR666777888',
                'lieu' => 'Atelier Qualité',
                'type' => 'Laser',
                'modele' => 'HL-L5100DN',
                'created_at' => Carbon::now()->subMonths(5),
                'updated_at' => Carbon::now()->subDay(),
            ],
            [
                'nom' => 'IMP-PROD-004',
                'entite' => 'Production',
                'statut' => 'Hors service',
                'fabricant' => 'HP',
                'reseau_ip' => null,
                'numero_serie' => 'SNHP444555666',
                'lieu' => 'Local Maintenance',
                'type' => 'Laser',
                'modele' => 'LaserJet 4200',
                'created_at' => Carbon::now()->subYears(5),
                'updated_at' => Carbon::now()->subMonths(6),
            ],

            // === RÉCEPTION & COMMUNS (8 imprimantes) ===
            [
                'nom' => 'IMP-REC-001',
                'entite' => 'Réception',
                'statut' => 'En service',
                'fabricant' => 'Brother',
                'reseau_ip' => '192.168.1.110',
                'numero_serie' => 'SNBR999888777',
                'lieu' => 'Poste Accueil Principal',
                'type' => 'Multifonction',
                'modele' => 'DCP-L3550CDW',
                'created_at' => Carbon::now()->subMonths(12),
                'updated_at' => Carbon::now()->subDays(5),
            ],
            [
                'nom' => 'IMP-REUNION-001',
                'entite' => 'Direction',
                'statut' => 'En service',
                'fabricant' => 'HP',
                'reseau_ip' => '192.168.1.120',
                'numero_serie' => 'SNHP333444555',
                'lieu' => 'Salle de Réunion Conseil',
                'type' => 'Laser',
                'modele' => 'LaserJet Enterprise M506dn',
                'created_at' => Carbon::now()->subMonths(7),
                'updated_at' => Carbon::now()->subHours(12),
            ],
            [
                'nom' => 'IMP-ARCHIVES-001',
                'entite' => 'Administration',
                'statut' => 'En service',
                'fabricant' => 'Canon',
                'reseau_ip' => '192.168.1.130',
                'numero_serie' => 'SNCA111222333',
                'lieu' => 'Salle Archives',
                'type' => 'Laser',
                'modele' => 'i-SENSYS LBP6030w',
                'created_at' => Carbon::now()->subYears(2),
                'updated_at' => Carbon::now()->subDays(20),
            ],
            [
                'nom' => 'IMP-CAFET-001',
                'entite' => 'Services Généraux',
                'statut' => 'En service',
                'fabricant' => 'Epson',
                'reseau_ip' => '192.168.1.140',
                'numero_serie' => 'SNEP444555666',
                'lieu' => 'Espace Cafétéria',
                'type' => 'Jet d\'encre',
                'modele' => 'WorkForce WF-2830',
                'created_at' => Carbon::now()->subMonths(9),
                'updated_at' => Carbon::now()->subDays(3),
            ],
            [
                'nom' => 'IMP-FORMATION-001',
                'entite' => 'Formation',
                'statut' => 'En service',
                'fabricant' => 'HP',
                'reseau_ip' => '192.168.1.150',
                'numero_serie' => 'SNHP555666777',
                'lieu' => 'Salle Formation 1',
                'type' => 'Laser',
                'modele' => 'LaserJet Pro MFP M130fw',
                'created_at' => Carbon::now()->subMonths(6),
                'updated_at' => Carbon::now()->subDays(7),
            ],
            [
                'nom' => 'IMP-FORMATION-002',
                'entite' => 'Formation',
                'statut' => 'En maintenance',
                'fabricant' => 'Canon',
                'reseau_ip' => '192.168.1.151',
                'numero_serie' => 'SNCA888999000',
                'lieu' => 'Salle Formation 2',
                'type' => 'Multifonction',
                'modele' => 'PIXMA TS8350',
                'created_at' => Carbon::now()->subMonths(4),
                'updated_at' => Carbon::now()->subDay(),
            ],
            [
                'nom' => 'IMP-BIBLIO-001',
                'entite' => 'Bibliothèque',
                'statut' => 'En service',
                'fabricant' => 'Brother',
                'reseau_ip' => '192.168.1.160',
                'numero_serie' => 'SNBR777888999',
                'lieu' => 'Bibliothèque d\'Entreprise',
                'type' => 'Laser',
                'modele' => 'HL-L8260CDW',
                'created_at' => Carbon::now()->subMonths(10),
                'updated_at' => Carbon::now()->subDays(15),
            ],
            [
                'nom' => 'IMP-SECURITE-001',
                'entite' => 'Sécurité',
                'statut' => 'En service',
                'fabricant' => 'HP',
                'reseau_ip' => '192.168.1.170',
                'numero_serie' => 'SNHP666777888',
                'lieu' => 'Poste de Sécurité Principal',
                'type' => 'Laser',
                'modele' => 'LaserJet Pro M15w',
                'created_at' => Carbon::now()->subMonths(8),
                'updated_at' => Carbon::now()->subDays(2),
            ],
        ];

        foreach ($imprimantes as $imprimante) {
            Imprimante::create($imprimante);
        }

        $this->command->info('🎯 ' . count($imprimantes) . ' imprimantes de test créées avec succès!');

        // Statistiques détaillées
        $stats = collect($imprimantes)->groupBy('statut')->map->count();
        $this->command->info('📊 Répartition par statut:');
        foreach ($stats as $statut => $count) {
            $this->command->info("   - {$statut}: {$count} imprimantes");
        }

        $entites = collect($imprimantes)->groupBy('entite')->map->count();
        $this->command->info('🏢 Répartition par entité:');
        foreach ($entites as $entite => $count) {
            $this->command->info("   - {$entite}: {$count} imprimantes");
        }

        $fabricants = collect($imprimantes)->groupBy('fabricant')->map->count();
        $this->command->info('🏭 Répartition par fabricant:');
        foreach ($fabricants as $fabricant => $count) {
            $this->command->info("   - {$fabricant}: {$count} imprimantes");
        }
    }
}
