<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class materielReseauSeeder extends Seeder
{
    /**
     * Exécuter le seed
     */
    public function run()
    {
        $materiels = [
            [
                'nom' => 'SW-CORE-01',
                'entite' => 'Informatique',
                'statut' => 'En service',
                'fabricant' => 'Cisco',
                'lieu' => 'Salle Serveur Principal',
                'reseau_ip' => '192.168.1.1',
                'type' => 'Switch',
                'modele' => 'Catalyst 2960X',
                'numero_serie' => 'FOC1234X5YZ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nom' => 'RT-INTERNET-01',
                'entite' => 'Réseau',
                'statut' => 'En service',
                'fabricant' => 'Cisco',
                'lieu' => 'Baie Telecom',
                'reseau_ip' => '10.0.0.1',
                'type' => 'Routeur',
                'modele' => 'ISR 4331',
                'numero_serie' => 'FOC5678A9BC',
                'created_at' => Carbon::now()->subDays(30),
                'updated_at' => Carbon::now()->subDays(2),
            ],
            [
                'nom' => 'AP-ETAGE1-01',
                'entite' => 'Communication',
                'statut' => 'En service',
                'fabricant' => 'Ubiquiti',
                'lieu' => 'Couloir Etage 1',
                'reseau_ip' => '192.168.1.10',
                'type' => 'Point d\'accès',
                'modele' => 'UniFi AC Pro',
                'numero_serie' => 'UAP-AC-PRO-12345',
                'created_at' => Carbon::now()->subDays(60),
                'updated_at' => Carbon::now()->subDays(5),
            ],
            [
                'nom' => 'FW-PRINCIPAL',
                'entite' => 'Sécurité',
                'statut' => 'En service',
                'fabricant' => 'Fortinet',
                'lieu' => 'Salle DMZ',
                'reseau_ip' => '192.168.0.1',
                'type' => 'Pare-feu',
                'modele' => 'FortiGate 60E',
                'numero_serie' => 'FG60E123456789',
                'created_at' => Carbon::now()->subDays(90),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'nom' => 'SW-SECOURS-01',
                'entite' => 'Informatique',
                'statut' => 'En stock',
                'fabricant' => 'HP',
                'lieu' => 'Local Technique',
                'reseau_ip' => null,
                'type' => 'Switch',
                'modele' => 'Aruba 2930F',
                'numero_serie' => 'CN1234A5B6C7',
                'created_at' => Carbon::now()->subDays(15),
                'updated_at' => Carbon::now()->subDays(10),
            ],
            [
                'nom' => 'AP-REUNION-01',
                'entite' => 'Communication',
                'statut' => 'En maintenance',
                'fabricant' => 'TP-Link',
                'lieu' => 'Salle Réunion A',
                'reseau_ip' => '192.168.1.25',
                'type' => 'Point d\'accès',
                'modele' => 'EAP245',
                'numero_serie' => 'TP1234567890',
                'created_at' => Carbon::now()->subDays(45),
                'updated_at' => Carbon::now()->subHours(6),
            ],
            [
                'nom' => 'SW-ADMIN-01',
                'entite' => 'Administration',
                'statut' => 'En service',
                'fabricant' => 'Netgear',
                'lieu' => 'Bureau IT',
                'reseau_ip' => '192.168.2.1',
                'type' => 'Switch',
                'modele' => 'GS324TP',
                'numero_serie' => 'NG123456789ABC',
                'created_at' => Carbon::now()->subDays(75),
                'updated_at' => Carbon::now()->subDays(20),
            ],
            [
                'nom' => 'RT-FILIALE-01',
                'entite' => 'Réseau',
                'statut' => 'Hors service',
                'fabricant' => 'MikroTik',
                'lieu' => 'Site Secondaire',
                'reseau_ip' => '172.16.1.1',
                'type' => 'Routeur',
                'modele' => 'RB4011',
                'numero_serie' => 'MTK123456789',
                'created_at' => Carbon::now()->subDays(120),
                'updated_at' => Carbon::now()->subDays(30),
            ],
            [
                'nom' => 'AP-EXTERIEUR-01',
                'entite' => 'Communication',
                'statut' => 'En service',
                'fabricant' => 'Ubiquiti',
                'lieu' => 'Parking Extérieur',
                'reseau_ip' => '192.168.1.50',
                'type' => 'Point d\'accès',
                'modele' => 'UniFi Mesh Pro',
                'numero_serie' => 'UAP-AC-M-PRO-67890',
                'created_at' => Carbon::now()->subDays(30),
                'updated_at' => Carbon::now()->subDays(3),
            ],
            [
                'nom' => 'SW-DATA-01',
                'entite' => 'Data Center',
                'statut' => 'En service',
                'fabricant' => 'Juniper',
                'lieu' => 'Data Center Principal',
                'reseau_ip' => '10.10.1.1',
                'type' => 'Switch',
                'modele' => 'EX4300',
                'numero_serie' => 'JNPR123456789',
                'created_at' => Carbon::now()->subDays(180),
                'updated_at' => Carbon::now()->subDays(7),
            ],
            [
                'nom' => 'MODEM-ADSL-01',
                'entite' => 'Réseau',
                'statut' => 'En service',
                'fabricant' => 'D-Link',
                'lieu' => 'Baie Telecom',
                'reseau_ip' => '192.168.100.1',
                'type' => 'Modem',
                'modele' => 'DSL-2888A',
                'numero_serie' => 'DL1234567890AB',
                'created_at' => Carbon::now()->subDays(200),
                'updated_at' => Carbon::now()->subDays(15),
            ],
            [
                'nom' => 'SW-REMPLACEMENT',
                'entite' => 'Informatique',
                'statut' => 'En stock',
                'fabricant' => 'Cisco',
                'lieu' => 'Local Stockage',
                'reseau_ip' => null,
                'type' => 'Switch',
                'modele' => 'Catalyst 2960L',
                'numero_serie' => 'FOC9999X5YZ',
                'created_at' => Carbon::now()->subDays(10),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'nom' => 'AP-CAFETERIA-01',
                'entite' => 'Communication',
                'statut' => 'En maintenance',
                'fabricant' => 'Ubiquiti',
                'lieu' => 'Cafétéria',
                'reseau_ip' => '192.168.1.75',
                'type' => 'Point d\'accès',
                'modele' => 'UniFi AC Lite',
                'numero_serie' => 'UAP-AC-LITE-54321',
                'created_at' => Carbon::now()->subDays(90),
                'updated_at' => Carbon::now()->subHours(12),
            ],
            [
                'nom' => 'FW-BACKUP',
                'entite' => 'Sécurité',
                'statut' => 'En stock',
                'fabricant' => 'Fortinet',
                'lieu' => 'Local Sécurité',
                'reseau_ip' => null,
                'type' => 'Pare-feu',
                'modele' => 'FortiGate 100F',
                'numero_serie' => 'FG100F987654321',
                'created_at' => Carbon::now()->subDays(30),
                'updated_at' => Carbon::now()->subDays(5),
            ],
            [
                'nom' => 'SW-VOIP-01',
                'entite' => 'Téléphonie',
                'statut' => 'En service',
                'fabricant' => 'Cisco',
                'lieu' => 'Salle Telecom',
                'reseau_ip' => '192.168.3.1',
                'type' => 'Switch',
                'modele' => 'Catalyst 3560CX',
                'numero_serie' => 'FOC8888B9CD',
                'created_at' => Carbon::now()->subDays(60),
                'updated_at' => Carbon::now()->subDays(8),
            ]
        ];

        // Insérer les données
        DB::table('materiels_reseau')->insert($materiels);

        $this->command->info('✅ 15 équipements réseau de test créés avec succès !');
    }
}
